try { require('dotenv').config(); } catch (e) { /* dotenvが無い環境では無視 */ }
const fs = require('fs');
const path = require('path');
const { fetchRakutenApi, RAKUTEN_APP_ID, RAKUTEN_AFFILIATE_ID } = require('./utils');
const { GoogleGenAI } = require('@google/genai');

const BASE_URL = 'https://tabi-plan.org';

function countXPoints(str) {
    if (!str) return 0;
    let points = 0;
    for (let i = 0; i < str.length; i++) {
        const code = str.charCodeAt(i);
        if ((code >= 0x0000 && code <= 0x007f) || (code >= 0xff61 && code <= 0xff9f)) {
            points += 1;
        } else {
            points += 2;
        }
    }
    return points;
}

async function generateXTweets(niche, hotel) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) return null;

    try {
        const ai = new GoogleGenAI({ apiKey });
        const prompt = `
以下の情報をもとに、X（旧Twitter）に投稿する「スレッド投稿（親ツイートと子ツイートの2件）」の文章を日本語で生成してください。
ユーザーの興味を惹きつけ、リンクをクリックして詳細を見たくなるような、洗練されたマーケティング文章（「ポチらせる」文章）を作成してください。

【対象の特設ページ（ニッチ条件）】
都市名: ${niche.cityName}
ターゲット層・キーワード: ${niche.keyword}
特設ページURL: ${BASE_URL}/${niche.city}/${niche.slug}/

【ピックアップホテル例】
ホテル名: ${hotel.name}
最安料金目安: ${Number(hotel.price).toLocaleString()} 円〜
クチコミ評価: ${hotel.reviewAverage || '4.0'} / 5.0
ホテルの特徴（楽天APIより）: ${hotel.special || 'なし'}

【作成ルール】
1. **親ツイート（tweet1）の作成ルール**:
   - そのキーワード（例：${niche.keyword}）で探している人の悩みに寄り添う、または魅力的な提案をするフック文章。
   - 文字数は**厳密に全角130文字以内**（合計260ポイント/バイト以内）に収めてください。
   - 文末に必ず以下のハッシュタグをスペース区切りで含めてください：
     #${niche.cityName}旅行 #ホテル選び
   - 「💡【AI解析】〜」などの機械的な固定文頭は避け、毎回新鮮なフックから書き始めてください。

2. **子ツイート（tweet2）の作成ルール**:
   - 今回ピックアップした「${hotel.name}」を例に挙げつつ、「この他にも条件に合う厳選宿をランキングでまとめています」と案内する文章。
   - 必ず以下の特設ページURLを含めてください（文字数カウントに含まれます）：
     ${BASE_URL}/${niche.city}/${niche.slug}/
   - URLを含めて**厳密に全角130文字以内**（合計260ポイント/バイト以内）に収めてください。

3. **表現のルール**:
   - プロの旅行ライターが発信しているような、リアルで魅力あふれる投稿文にしてください。
   - 「バグ級」「コスパバグり」「発見！」といった安易な煽り文句は厳禁です。

【出力フォーマット】
以下のJSONフォーマット（プレーンなJSONオブジェクトのみ、Markdownの\`\`\`json等のコードブロック囲みは不要）で出力してください。

{
  "tweet1": "生成された親ツイートの文章（ハッシュタグを含む、130文字以内）",
  "tweet2": "生成された子ツイートの文章（URLとホテル名を含む、130文字以内）"
}
`;

        const response = await ai.models.generateContent({
            model: 'gemini-2.0-flash',
            contents: prompt,
            config: {
                responseMimeType: 'application/json'
            }
        });

        const jsonText = response.text;
        const cleanedJson = jsonText.replace(/\`\`\`json/g, '').replace(/\`\`\`/g, '').trim();
        const parsedData = JSON.parse(cleanedJson);
        
        if (parsedData.tweet1 && parsedData.tweet2) {
            return parsedData;
        }
    } catch (e) {
        console.error('Error generating tweets via Gemini:', e.message);
    }
    return null;
}

async function run() {
    console.log('Generating daily X post drafts (V2 Niche Focus)...');

    const configPath = path.join(__dirname, 'niche_config.json');
    const niches = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    const nicheKeys = Object.keys(niches);

    // 毎日ローテーションでニッチを選ぶ
    const now = new Date();
    const jstDate = new Date(now.toLocaleString('en-US', { timeZone: 'Asia/Tokyo' }));
    const msInDay = 24 * 60 * 60 * 1000;
    const epochDays = Math.floor((jstDate.getTime() + 9 * 60 * 60 * 1000) / msInDay);
    
    // はてなブログとは別のニッチが選ばれるように少しオフセットをかける
    const selectedKey = nicheKeys[(epochDays + 3) % nicheKeys.length];
    const niche = niches[selectedKey];

    console.log(`Target Niche: ${niche.cityName} - ${niche.keyword}`);

    const url = 'https://openapi.rakuten.co.jp/engine/api/Travel/KeywordHotelSearch/20170426';
    const params = {
        applicationId: RAKUTEN_APP_ID,
        accessKey: 'pk_5MWJwVdIjLhdoj7Zg1RriahaHY2JahwsKyl6c3KDRkG',
        affiliateId: RAKUTEN_AFFILIATE_ID,
        format: 'json',
        keyword: niche.searchParams.keyword,
        hits: 10
    };

    let hotels = await fetchRakutenApi(url, params, niche.filters.minReview, 'standard', 1);
    if (!hotels || hotels.length === 0) {
        hotels = await fetchRakutenApi(url, params, niche.fallbackFilters.minReview, 'standard', 1);
    }
    
    if (!hotels || hotels.length === 0) {
        console.log('No hotels found. Exiting.');
        return;
    }

    const hotel = hotels[0];
    
    // AIによる生成を実行
    const aiTweets = await generateXTweets(niche, hotel);
    let tweet1 = '', tweet2 = '';
    
    if (aiTweets && countXPoints(aiTweets.tweet1) <= 280 && countXPoints(aiTweets.tweet2) <= 280) {
        console.log(`[AI] ✅ Dynamic tweets successfully generated by Gemini!`);
        tweet1 = aiTweets.tweet1;
        tweet2 = aiTweets.tweet2;
    } else {
        console.log(`[AI] ⚠️ Falling back to static templates.`);
        tweet1 = `✨ 今日の宿選び
${niche.cityName}で「${niche.keyword}」をお探しですか？
評価★${hotel.reviewAverage || '-'}で1泊${Number(hotel.price).toLocaleString()}円〜と、非常に満足度の高い宿泊プランを見つけました。
詳細はスレッドにて👇
#${niche.cityName}旅行 #ホテル選び`;
        tweet2 = `🏨 ${hotel.name}

▼AI厳選の最安値プラン確認と、この条件に合うその他のおすすめホテルランキングはこちら👇
${BASE_URL}/${niche.city}/${niche.slug}/

宿泊費を賢く抑えた予算で、極上の体験を。Tabi Plan公式サイトで特設ガイド公開中✨`;
    }

    const dateStr = `${jstDate.getMonth() + 1}月${jstDate.getDate()}日投稿分`;

    let summaryMarkdown = `
# 📝 X投稿用原稿：${dateStr} (Buffer用 - ニッチ訴求版)
最新の高評価データに基づいた「特設ページ誘導型」のスレッド形式投稿原稿です。

---

## 1. 【親ツイート】（興味付け・フック）
以下の文章をコピーし、**${niche.cityName}の美しい風景画像** または **ホテルの写真** を1枚添付して投稿してください。

\`\`\`text
${tweet1}
\`\`\`

*(文字数目安: 約 ${Math.ceil(countXPoints(tweet1) / 2)} 文字 / 140文字以内)*

---

## 2. 【子ツイート】（詳細・特設ページへの送客）
上記ツイートの「返信（スレッド追加）」として、以下の文章を繋げてください。
※URLを貼ることで、X上で自動的に「特設ページのOGP画像（リンクカード）」が表示されます。

\`\`\`text
${tweet2}
\`\`\`

---
> [!TIP]
> **Bufferでのコツ**: 「Create Post」で1つ目の文章を入力した後、右下の「Add thread item」を押すと連投が作成できます。
`;

    if (process.env.GITHUB_STEP_SUMMARY) {
        fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, summaryMarkdown);
    } else {
        console.log(summaryMarkdown);
    }
}

run();
